version: '2.1'

services:
    golang.stresstestdemo.com:
        build:
            context: .
        container_name: golang.stresstestdemo.com
        image: stress-test-demo/golang
        ports:
            - "127.0.0.1:3002:3002"
        cpu_shares: 10
        cpu_quota: 50000
        cpuset: 0,1
        mem_limit: 10m
        memswap_limit: 0m
